### ISSUE TITLE
Header not properly validate

### ISSUE THREAD

**Issue by fredcido** [hkarlstrom/openapi-validation-middleware#20]
I am trying to use the lib to validate some headers in the request using Slim 3.12.
This is how the parameter looks like in my `openapi`:

```yaml
components:
  parameters:
    X-Location-Code:
      in: header
      name: X-Location-Code
      schema:
        type: string
        pattern: '^[A-Z]{3}$'
      required: true
```

This is my request:

```
GET /references/en/SIPStatus HTTP/1.1
Host: localhost:8000
X-Location-Code: DIL
```

And still, I'm getting an error saying that the header `X-Location-Code` was not found. I know that Slim converts the header to lowecase and allow to fetch them regardless. 
When checking the code, at the `OpenApiValidation.php` line  `236`, we can see:

```php
$properties[] = Property::fromParameter($p, $values[$p->in][$p->name] ?? null);
``` 

But that $values variable doesn't seem to host the headers values.
