### ISSUE TITLE
Boolean parameter in query string

### ISSUE THREAD

**Issue by francescozanoni** [hkarlstrom/openapi-validation-middleware#24]
Hi, man.

I've got this parameter declaration within my OpenAPI schema (full schema [here](https://github.com/francescozanoni/students-api-php/blob/feature/lumen58/public/openapi.yaml.example)):
````yaml
components:
  parameters:
    withAudits:
      in: query
      name: with_audits
      schema:
        type: boolean
      required: false
````
but, when I use it within my request, e.g. `curl http://localhost/annotations/1?with_audits=true`, I get the following validation error:
````
# Output of print_r($validator->validateRequest($request, $path, $method, $pathParameters))

Array (
  [0] => Array (
    [name] => with_audits
    [code] => error_type
    [value] => true
    [in] => query
    [expected] => boolean
    [used] => string
  )
)
````
Thanks in advance.

Francesco
