### ISSUE TITLE
using the nullable attribute on a property with a format causes crash when posting with form-data encoding

### ISSUE THREAD

**Issue by darkbluesun** [hkarlstrom/openapi-validation-middleware#45]
When I make a POST to my route using form-data encoding instead of JSON, *and* I am using the `nullable` attribute, *and* I have set a format, I receive a TypeError.

Argument 1 passed to HKarlstrom\\Middleware\\OpenApiValidation::checkFormat() must be of the type string, array given, called in /var/www/vendor/hkarlstrom/openapi-validation-middleware/src/OpenApiValidation.php on line 343
#0 /var/www/vendor/hkarlstrom/openapi-validation-middleware/src/OpenApiValidation.php(343): HKarlstrom\\Middleware\\OpenApiValidation->checkFormat(Array, 'date-time')

```
    MyObject:
      required:
        - amount
        - userId
        - methodId
        - date
        amount:
          type: number
        userId:
          type: integer
        methodId:
          description: 'Payment Method ID. Set to null to use existing method. Set to ''DD'' for direct debit'
          type: string
          nullable: true
        date:
          description: 'Date in ISO 8601 format. Set to null for immediate processing'
          type: string
          format: date-time
          nullable: true
```
Note this field still could be provided, but allowed to be null. It works fine when submitting a raw json request. https://swagger.io/docs/specification/data-models/data-types/#null

The problem appears to be here:
```
    private function validateProperties(array $properties) : ?array
    {
        $errors = [];
        foreach ($properties as $property) {
            if (isset($property->schema->type, $property->schema->format)) {
                $this->checkFormat($property->schema->type, $property->schema->format);
```
```
object(HKarlstrom\Middleware\OpenApiValidation\Property)[527]
  public 'name' => string 'date (length=11)
  public 'in' => string 'form-data' (length=9)
  public 'required' => boolean false
  public 'schema' => 
    object(stdClass)[528]
      public 'description' => string 'Date in ISO 8601 format. Set to null for immediate processing' (length=66)
      public 'type' => 
        array (size=2)
          0 => string 'string' (length=6)
          1 => string 'null' (length=4)
      public 'format' => string 'date-time' (length=9)
  public 'value' => null```
